apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: terraorbit-service-monitor
  labels:
    app: terraorbit
    release: prometheus
spec:
  selector:
    matchLabels:
      app: terraorbit
  namespaceSelector:
    matchNames:
      - terraorbit
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  sampleLimit: 1000
  targetLimit: 100
  scrapeTimeout: 10s 