apiVersion: v1
kind: Service
metadata:
  name: terraorbit-metrics
  labels:
    app: terraorbit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: terraorbit
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  type: ClusterIP 